# -*- mode: Makefile; -*-
# Copyright (c) 2011 Bitcoin Developers
# Distributed under the MIT/X11 software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

# Mac OS X makefile for RNRC
# Originally by Laszlo Hanyecz (solar@heliacal.net)
#
# Defaults target MacPorts (/opt/local). For Homebrew, compile-macos.sh
# overrides OPENSSL_*/BOOST_*/BDB_* paths and library suffixes.

CXX ?= c++
CC ?= cc

DEPSDIR ?= /opt/local
OPENSSL_INCLUDE_PATH ?= $(DEPSDIR)/include
OPENSSL_LIB_PATH ?= $(DEPSDIR)/lib
BOOST_INCLUDE_PATH ?= $(DEPSDIR)/include
BOOST_LIB_PATH ?= $(DEPSDIR)/lib
BDB_INCLUDE_PATH ?= $(DEPSDIR)/include/db48
BDB_LIB_PATH ?= $(DEPSDIR)/lib/db48
BOOST_LIB_SUFFIX ?= -mt
BDB_LIB_SUFFIX ?= -4.8
MACOSX_DEPLOYMENT_TARGET ?= 10.15

INCLUDEPATHS= \
 -I"$(CURDIR)" \
 -I"$(CURDIR)"/obj \
 -I"$(OPENSSL_INCLUDE_PATH)" \
 -I"$(BDB_INCLUDE_PATH)" \
 -I"$(BOOST_INCLUDE_PATH)"

LIBPATHS= \
 -L"$(OPENSSL_LIB_PATH)" \
 -L"$(BDB_LIB_PATH)" \
 -L"$(BOOST_LIB_PATH)"

USE_UPNP:=-
USE_IPV6:=1

LIBS= -dead_strip

ifdef STATIC
# Build STATIC if you are redistributing the RNRCd binary
LIBS += \
 $(BDB_LIB_PATH)/libdb_cxx$(BDB_LIB_SUFFIX).a \
 $(BOOST_LIB_PATH)/libboost_system$(BOOST_LIB_SUFFIX).a \
 $(BOOST_LIB_PATH)/libboost_filesystem$(BOOST_LIB_SUFFIX).a \
 $(BOOST_LIB_PATH)/libboost_program_options$(BOOST_LIB_SUFFIX).a \
 $(BOOST_LIB_PATH)/libboost_thread$(BOOST_LIB_SUFFIX).a \
 $(BOOST_LIB_PATH)/libboost_chrono$(BOOST_LIB_SUFFIX).a \
 $(OPENSSL_LIB_PATH)/libssl.a \
 $(OPENSSL_LIB_PATH)/libcrypto.a \
 -lz
else
LIBS += \
 -ldb_cxx$(BDB_LIB_SUFFIX) \
 -lboost_system$(BOOST_LIB_SUFFIX) \
 -lboost_filesystem$(BOOST_LIB_SUFFIX) \
 -lboost_program_options$(BOOST_LIB_SUFFIX) \
 -lboost_thread$(BOOST_LIB_SUFFIX) \
 -lboost_chrono$(BOOST_LIB_SUFFIX) \
 -lssl \
 -lcrypto \
 -lz
endif

DEFS=-DMAC_OSX -DMSG_NOSIGNAL=0 -DBOOST_SPIRIT_THREADSAFE -DBOOST_BIND_GLOBAL_PLACEHOLDERS

ifdef RELEASE
CFLAGS = -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET) -O2
else
CFLAGS = -g
endif

CFLAGS += -std=c++17 -Wall -Wextra -Wformat -Wno-ignored-qualifiers -Wformat-security \
    -Wno-unused-parameter -Wno-deprecated-declarations \
    $(DEBUGFLAGS) $(DEFS) $(INCLUDEPATHS)

OBJS= \
    obj/alert.o \
    obj/version.o \
    obj/checkpoints.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/crypter.o \
    obj/key.o \
    obj/db.o \
    obj/init.o \
    obj/irc.o \
    obj/keystore.o \
    obj/main.o \
    obj/miner.o \
    obj/net.o \
    obj/protocol.o \
    obj/bitcoinrpc.o \
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpcblockchain.o \
    obj/rpcrawtransaction.o \
    obj/script.o \
    obj/sync.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/noui.o \
    obj/pbkdf2.o \
    obj/kernel.o \
    obj/scrypt.o \
    obj/scrypt-x86.o \
    obj/scrypt-x86_64.o \
    obj/zerocoin/Accumulator.o \
    obj/zerocoin/AccumulatorProofOfKnowledge.o \
    obj/zerocoin/Coin.o \
    obj/zerocoin/CoinSpend.o \
    obj/zerocoin/Commitment.o \
    obj/zerocoin/ParamGeneration.o \
    obj/zerocoin/Params.o \
    obj/zerocoin/SerialNumberSignatureOfKnowledge.o \
    obj/zerocoin/SpendMetaData.o \
    obj/zerocoin/ZeroTest.o

ifndef USE_UPNP
	override USE_UPNP = -
endif
ifneq (${USE_UPNP}, -)
	DEFS += -DUSE_UPNP=$(USE_UPNP)
ifdef STATIC
	LIBS += $(DEPSDIR)/lib/libminiupnpc.a
else
	LIBS += -lminiupnpc
endif
endif

all: RNRCd

LIBS += $(CURDIR)/leveldb/libleveldb.a $(CURDIR)/leveldb/libmemenv.a
DEFS += $(addprefix -I,$(CURDIR)/leveldb/include)
DEFS += $(addprefix -I,$(CURDIR)/leveldb/helpers)
OBJS += obj/txdb-leveldb.o
leveldb/libleveldb.a:
	@echo "Building LevelDB ..."; \
	  cd leveldb; \
	  CC=$(CC) CXX=$(CXX) TARGET_OS=Darwin \
	    CXXFLAGS="-std=c++17 -Wno-error -Wno-deprecated-declarations -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET)" \
	    $(MAKE) libleveldb.a libmemenv.a; \
	  cd ..
obj/txdb-leveldb.o: leveldb/libleveldb.a

# auto-generated dependencies:
-include obj/*.P
-include obj/zerocoin/*.P

obj/build.h: FORCE
	/bin/sh ../share/genbuild.sh obj/build.h
version.cpp: obj/build.h
DEFS += -DHAVE_BUILD_INFO

obj/%.o: %.cpp
	$(CXX) -c $(CFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

obj/zerocoin/%.o: zerocoin/%.cpp
	$(CXX) -c $(CFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

obj/scrypt-x86.o: scrypt-x86.S
	$(CXX) -c $(CFLAGS) -o $@ $<

obj/scrypt-x86_64.o: scrypt-x86_64.S
	$(CXX) -c $(CFLAGS) -o $@ $<

RNRCd: $(OBJS:obj/%=obj/%)
	$(CXX) $(CFLAGS) -o $@ $(LIBPATHS) $^ $(LIBS)

clean:
	-rm -f RNRCd
	-rm -f obj/*.o
	-rm -f obj/zerocoin/*.o
	-rm -f obj/*.P
	-rm -f obj/zerocoin/*.P
	-rm -f obj/build.h

FORCE:
